// js/main.js
import './modules/guestbook-panel.js';
import './modules/time.js';
import './modules/vanta-bg.js';
import './modules/card-toggle.js';
import './modules/image-compress.js';
import './modules/net-monitor.js';
import './modules/pdf-convert.js';
import './modules/music-player.js';
import './modules/dog-speak.js';
import './modules/encryption.js';
import './modules/mirage-generator.js';
import './modules/ghost-text.js';
